apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-process-train-deployment
  labels:
    app: pipeline-data-process
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pipeline-data-process
  template:
    metadata:
      labels:
        app: pipeline-data-process
    spec:
      volumes:
        - name: pvc
          persistentVolumeClaim:
            claimName: pvc-kubeflow-pipe-app
      containers:
      - name: data-process-train
        image: majinetudacitylearn/pipeline_data_preprocessing_train:v0.0.1
        imagePullPolicy: Always
        volumeMounts:
          - name: pvc
            mountPath: /app