FROM python:3.9-slim-buster

WORKDIR pipelines

RUN pip3 install kfp==2.0.0b13 --upgrade --user
RUN echo 'export PATH=$PATH:~/.local/bin' | tee -a ~/.bashrc

COPY ./pipelines/ml_pipeline_components ml_pipeline_components
COPY ./pipelines/data_preprocessing_train.py .

CMD [ "python3", "data_preprocessing_train.py"]