#FROM python:3.9-slim-buster
FROM alpine:latest

WORKDIR pipelines

RUN apk add --update python3=~3.9 py3-pip
RUN pip3 install pandas fastparquet kfp minio --upgrade --user
RUN echo 'export PATH=$PATH:~/.local/bin' | tee -a ~/.bashrc

COPY ./pipelines/file_uploader.py .

CMD ["python3", "file_uploader.py", "--train-path", "/data", "--train-filename", "train", "--test-path", "/data", "--test-filename", "test"]