#FROM python:3.9-slim-buster
FROM alpine:latest

WORKDIR pipelines

RUN apk add --update python3=~3.9 py3-pip
RUN pip3 install kfp --upgrade --user
RUN echo 'export PATH=$PATH:~/.local/bin' | tee -a ~/.bashrc

COPY ./pipelines/ml_pipeline_components ml_pipeline_components
COPY ./pipelines/data_preprocessing_train.py .

CMD [ "python3", "data_preprocessing_train.py"]