apiVersion: batch/v1
kind: Job
metadata:
  name: job-titanic-model
spec:
  parallelism: 1
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      labels:
        app: titanic-model
    spec:
      volumes:
      - name: pvc-app
        persistentVolumeClaim:
          claimName: pvc-kubeflow-pipe-app
      - name: pvc-data
        persistentVolumeClaim:
          claimName: pvc-kubeflow-pipe-data
      containers:
      - name: titanic-model
        image: majinetudacitylearn/titanic_model:v0.0.1
        command:
          - "python3"
          - "titanic_model.py"
          - "--minio-access-key=${MINIO_ACCESS_KEY_ID}"
          - "--minio-secret-key=${MINIO_SECRET_ACCESS_KEY}"
        env:
        - name: `MINIO_ACCESS_KEY_ID`
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: AWS_ACCESS_KEY_ID
        - name: MINIO_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: AWS_SECRET_ACCESS_KEY
        imagePullPolicy: Always
        volumeMounts:
        - name: pvc-app
          mountPath: /app
      restartPolicy: Never
  backoffLimit: 0