FROM majinetudacitylearn/module_ml_pipeline_components:v0.0.1

WORKDIR /app/data_preprocessing_train

COPY . .

RUN ls /
RUN ls /app
RUN ls /app/data_preprocessing_train

#CMD [ "python3", "data_preprocessing_train.py"]