apiVersion: batch/v1
kind: Job
metadata:
  name: job-data-process-train
spec:
  parallelism: 1
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      labels:
        app: pipeline-data-process
    spec:
      volumes:
      - name: pvc-app
        persistentVolumeClaim:
          claimName: pvc-kubeflow-pipe-app
      - name: pvc-data
        persistentVolumeClaim:
          claimName: pvc-kubeflow-pipe-data
      containers:
      - name: build-train-data
        image: majinetudacitylearn/pipeline_train_data:v0.0.1
        imagePullPolicy: Always
        volumeMounts:
        - name: pvc-app
          mountPath: /app
      restartPolicy: Never
  backoffLimit: 0