apiVersion: batch/v1
kind: Job
metadata:
  name: data-process-train-deployment
spec:
  parallelism: 1
  ttlSecondsAfterFinished: 300
  selector:
    matchLabels:
      app: pipeline-data-process
  template:
    metadata:
      labels:
        app: pipeline-data-process
    spec:
      volumes:
      - name: pvc
        persistentVolumeClaim:
          claimName: pvc-kubeflow-pipe-app
      containers:
      - name: data-process-train
        image: majinetudacitylearn/pipeline_data_preprocessing_train:v0.0.1
        imagePullPolicy: Always
        volumeMounts:
        - name: pvc
          mountPath: /app
      restartPolicy: Never
  backoffLimit: 3