apiVersion: batch/v1
kind: Job
metadata:
  name: job-feast-materialize
spec:
  parallelism: 1
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      labels:
        app: pipeline-feast-materialize
    spec:
      volumes:
      - name: pvc-app
        persistentVolumeClaim:
          claimName: pvc-kubeflow-pipe-app
      - name: pvc-data
        persistentVolumeClaim:
          claimName: pvc-kubeflow-pipe-data
      containers:
      - name: feast-materialize
        image: majinetudacitylearn/feast_materialize:v0.0.1
        imagePullPolicy: Always
        volumeMounts:
        - name: pvc-data
          mountPath: /data
      restartPolicy: Never
  backoffLimit: 0