apiVersion: "kubeflow.org/v1beta1"
kind: Experiment
metadata:
  namespace: kubeflow
  name: titanic_model- bayesianoptimization
spec:
  objective:
    type: maximize
    goal: 0.70
    objectiveMetricName: Validation-accuracy
    additionalMetricNames:
      - Train-accuracy
  algorithm:
    algorithmName: bayesianoptimization
    algorithmSettings:
      - name: "random_state"
        value: "10"
  parallelTrialCount: 3
  maxTrialCount: 12
  maxFailedTrialCount: 3
  parameters:
    - name: lr
      parameterType: double
      feasibleSpace:
        min: "0.01"
        max: "0.03"
    - name: optimizer
      parameterType: categorical
      feasibleSpace:
        list:
          - sgd
          - adam
          - ftrl
  trialTemplate:
    primaryContainerName: titanic_model
    trialParameters:
      - name: learningRate
        description: Learning rate for the training model
        reference: lr
      - name: optimizer
        description: Training model optimizer (sdg, adam or ftrl)
        reference: optimizer
    trialSpec:
      apiVersion: batch/v1
      kind: Job
      spec:
        template:
          spec:
            containers:
              - name: titanic_model
                image: majinetudacitylearn/titanic_model:v0.1
                command:
                  - "python3"
                  - "/app/titanic_model.py"
                  - "--batch-size=64"
                  - "--lr=${trialParameters.learningRate}"
                  - "--optimizer=${trialParameters.optimizer}"
            restartPolicy: Never