name: Build Pipelines components

on:
  workflow_dispatch:
  #push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.9" ]
    environment: development

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push (ml_pipeline_components)
        uses: docker/build-push-action@v4
        with:
          context: .
          file: pipelines/ml_pipeline_components/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/module_ml_pipeline_components:v0.0.1
      - name: Build and push (data_preprocessing_train)
        uses: docker/build-push-action@v4
        with:
          context: .
          file: pipelines/data_preprocessing_train/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pipeline_data_preprocessing_train:v0.0.1