name: Run Data Preprocessing Pipeline

on:
  workflow_dispatch:
  #workflow_run:
  #  workflows: [Build Pipelines components]
  #  types:
  #    - completed

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.9" ]
    environment: development

    steps:
      - uses: actions/checkout@v3
      - name: deploy file to server
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: 'ubuntu'
          server: ${{ vars.AWS_EC2_CONTROL_PLANE_IP }}
          ssh_private_key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
          local_path: './jobs/*'
          remote_path: '/home/ubuntu/jobs'
          sftpArgs: '-o ConnectTimeout=5'
      - name: run Pipeline (file upload)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.AWS_EC2_CONTROL_PLANE_IP }}
          username: ${{ vars.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
          script: |
            kubectl apply -f jobs/pipelines/file_uploader.yaml         
            sleep 60
            kubectl wait --for=condition=complete --timeout=2400s job/job-file-uploader
      - name: run Pipeline (data preprocessing)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.AWS_EC2_CONTROL_PLANE_IP }}
          username: ${{ vars.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
          script: |
            kubectl apply -f jobs/pipelines/data_processing_train.yaml
            sleep 590
            #kubectl wait --for=condition=complete --timeout=2400s job/job-data-process-train
            #kubectl wait --for=jsonpath='{.status.phase}'=Succeeded --timeout=2400s pod -l "pipelines.kubeflow.org/pipeline-sdk-type=kfp" -n admin
      - name: run Pipeline (feast apply)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.AWS_EC2_CONTROL_PLANE_IP }}
          username: ${{ vars.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
          script: |
            kubectl apply -f jobs/pipelines/feast_apply.yaml
            sleep 60
            kubectl wait --for=condition=complete --timeout=300s job/job-feast-apply
            #kubectl wait --for=jsonpath='{.status.phase}'=Succeeded --timeout=2400s pod -l "pipelines.kubeflow.org/pipeline-sdk-type=kfp" -n admin
      - name: run Pipeline (build train data)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.AWS_EC2_CONTROL_PLANE_IP }}
          username: ${{ vars.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
          script: |      
            kubectl apply -f jobs/pipelines/build_train_data.yaml
      - name: run Pipeline (feast materialize)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.AWS_EC2_CONTROL_PLANE_IP }}
          username: ${{ vars.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
          script: |
            kubectl apply -f jobs/pipelines/feast_materialize.yaml