name: Build Data Preprocessing Pipeline

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Build Pipelines components]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.9" ]
    environment: development

    steps:
      - uses: actions/checkout@v3
      - name: deploy file to server
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: 'ubuntu'
          server: ${{ vars.AWS_EC2_CONTROL_PLANE_IP }}
          ssh_private_key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
          local_path: './jobs/*'
          remote_path: '/home/ubuntu/jobs'
          sftpArgs: '-o ConnectTimeout=5'
      - name: run Pipeline
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.AWS_EC2_CONTROL_PLANE_IP }}
          username: ${{ vars.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
          script: |
            kubectl apply -f jobs/pipelines/file_uploader.yaml         
            sleep 60
            kubectl wait --for=jsonpath='{.status.phase}'=Completed --timeout=2400s job/job-file-uploader
            
            kubectl apply -f jobs/pipelines/data_processing_train.yaml
            sleep 60
            kubectl wait --for=jsonpath='{.status.phase}'=Completed --timeout=2400s job/job-data-process-train            
            until kubectl get pods --all -n admin -o jsonpath='{.status.conditions[?(@.type=="Complete")].status}' | grep True ; do sleep 60; done
            
            kubectl apply -f jobs/pipelines/feast_apply.yaml
            sleep 60
            kubectl wait --for=jsonpath='{.status.phase}'=Completed --timeout=2400s job/job-feast-apply
            until kubectl get pods --all -n admin -o jsonpath='{.status.conditions[?(@.type=="Complete")].status}' | grep True ; do sleep 60; done
            
            kubectl apply -f jobs/pipelines/build_train_data.yaml